#!/usr/bin/env bash

[[ -z $1 ]] && echo "A recipe must be specified" && exit 1
[[ $# -gt 1 ]] && echo "Only one argument allowed" && exit 1

RECIPE="$1"
REPO_PATH="/mnt/repo/$RECIPE"
BUILDER_IMAGE=arkdep-builder

[[ ! -d $REPO_PATH ]] && mkdir "$REPO_PATH"

# Build builder image if needed
! sudo podman inspect "$BUILDER_IMAGE" >/dev/null 2>&1 && sudo podman build -t "$BUILDER_IMAGE" .

# Build recipe image
sudo podman run \
    --privileged --rm \
    -v "$(pwd)"/arkdep-build.d:/root/arkdep-build.d:Z \
    -v "$REPO_PATH":/root/target:Z \
    "$BUILDER_IMAGE" "$RECIPE"
