# On es desen els snapshots
snapshot_dir		/arkdep/snapshots

# Només crea snapshot si hi ha canvis
snapshot_create		onchange

# Retenció local (7 dies)
snapshot_preserve_min	2d
snapshot_preserve	7d

# Definició del volum pare
# Fem servir el punt de muntatge real per a més claredat
volume /home/roger
    # btrbk buscarà el subvolum .gnupg dins de /home/roger/
    subvolume .gnupg
